### PR TITLE
Using latency results from check function to prioritize dialers

### PR DESCRIPTION
**Pull request by oxtoacart**
****\* THIS PR REMOVES FILES. BALANCER HAS BEEN MOVED TO FLASHLIGHT *****

Note - this is cumulative with #1, so you can either merge that one first to see just the changes related to the dialer prioritization, or you can just merge this PR and ignore #1.

Part of resolving getlantern/lantern#5174

Instead of using dial times to the proxies, we rely on the latency reported by the check function. In practice, this will allow us to test end-to-end round trip times which provide a more accurate picture.

Also, we now run checks more frequently.

### CODE REVIEW

**Comment by myleshorton** [comment]
What do you think about moving this whole repo into flashlight as just a new package @oxtoacart? I feel like we might as well just progressively do that as we come across packages that don't fully stand on their own.

**Comment by oxtoacart** [comment]
@myleshorton I don't have a strong feeling about moving this into flashlight. It seems to stand alone okay, and since it's working as-is right now, I'm inclined to just get the PR done and the fix in. We may want to do a single effort at some point to pull in everything that we want to pull in at once and just doing a single round of testing to make sure everything still looks good.

**Comment by myleshorton** [comment]
I guess by "stand alone" I mean likely that someone else would use this in their own project. That seems unlikely to me as is. It also seems like if we pull things in as we go it'll be less error prone than doing it all at once but also has the advantage that we'll likely pull in projects that we use more frequently. I also don't feel super strongly, but I would lean towards the side of pulling it in now so we don't have to worry about it later (it will immediately pay dividends as soon as we touch balancer again).

**Comment by oxtoacart** [comment]
Okay, I'll pull it in this morning. How comprehensively do you want me to integrate it? I could just move it into the local repo and leave the API mostly as is.

**Comment by myleshorton** [comment]
Yeah I would just leave it pretty much exactly as-is @oxtoacart, and now that you're doing it this already feels right just in terms of being able to review a single PR. Thanks!

**Comment by oxtoacart** [comment]
@myleshorton Done.

**Comment by oxtoacart** [comment]
@myleshorton If you want to see the delta vs the previous balancer code, you can look at this one commit - https://github.com/getlantern/balancer/pull/2/commits/d5afcc5b8db8c0be66e18f57e8026b01ae0449ae

**Pull request closed without merging**
